global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-2
        access_key:AKIARLB44ZBQNJU472GV
        secret_key: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
        port: 9100
